blank_issues_enabled: false
contact_links:
  - name: DM Holdings Community Forum
    url: https://github.community/
    about: Ask questions and discuss the roadmap here.
  - name: DM Holdings Feedback
    url: https://github.com/dmholdings/feedback/discussions
    about: Share your feedback with the DM Holdings team.